package template

import (
	"regexp"
	"strings"
)

var bootstrapSrc = `<?php
// generated by laravel-ls template compiler. Do not edit.
error_reporting(E_ERROR | E_PARSE);
require_once 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

__SOURCE__`

var (
	regexComment    = regexp.MustCompile(`(?m)^\s*//.*$`)
	regexEmptyLines = regexp.MustCompile(`\n+`)
)

func Compile(source []byte) []byte {
	return []byte(CompileString(string(source)))
}

func CompileString(source string) string {
	source = strings.TrimSpace(source)
	source, _ = strings.CutPrefix(source, "<?php")

	source = regexComment.ReplaceAllString(source, "")
	source = regexEmptyLines.ReplaceAllString(source, "\n")

	return strings.Replace(bootstrapSrc, "__SOURCE__", source, 1)
}
