name: Test

permissions:
  contents: read

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.22"]
        os: [ ubuntu-24.04, windows-latest ]
        arch: [ amd64 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}} go v${{ matrix.go-version }})
    env:
      GOARCH: ${{matrix.arch}}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: go test -v ./...
